### ISSUE TITLE
Multiple issues when specifying images

### ISSUE THREAD

**Issue by TheLQ** [xaque208/puppet-pxe#14]
According to the homepage if I want to deploy ubuntu my config needs to look like this
````
include pxe
$ubuntu = {
  "arch" => ["amd64","i386"],
  "ver"  => ["hardy","karmic","lucid","maverick","natty","oneiric","precise"],
  "os"   => "ubuntu"
}
resource_permute('pxe::images', $ubuntu)
````
Issue 1: This fails with `resource_permute(): wrong number of arguments (2; must be 3) `

So I added the $ubuntu_common hash from `tests/init.pp`:
````
include pxe
$ubuntu = {
  "arch" => ["amd64","i386"],
  "ver"  => ["hardy","karmic","lucid","maverick","natty","oneiric","precise"],
  "os"   => "ubuntu"
}
$ubuntu_common = {
  file => "os_<%= os %>",
  kernel => "images/<%= os %>/<%= ver %>/<%= arch %>/linux",
  append => "vga=791 initrd=images/<%= os %>/<%= ver %>/<%= arch %>/initrd.gz auto locale=en_US console-setup/layoutcode=us netcfg/get_hostname=debian url=http://urd.puppetlabs.lan/seed/ubuntu_base.cfg text",
}
resource_permute('pxe::images', $ubuntu, $ubuntu_common)
````
Issue 2: This fails with `undefined method 'each' for "ubuntu":String`. I tried changing the os to `["ubuntu"]` but unsurprisingly this fails with `Invalid parameter file`. I'm not sure which way is correct

Issue 3: The homepage says to add to `pxe::images` but `tests/init.pp` says `pxe::bootstrap`, which fails with `Invalid resource type pxe::bootstrap`. I'm assuming the home page is correct but I'm not sure

What I'm wondering is why the homepage says "Build: Passing" when clearly the tests don't work. It seems travis-ci is only checking for code correctness and style, but not if the tests runs without errors. This seems a little misleading for both you and users.

**Comment by xaque208** [comment]
I believe this was resolved in #15
