### ISSUE TITLE
Migrating from 0.1.1 to 0.1.2

### ISSUE THREAD

**Issue by djjudas21** [xaque208/puppet-pxe#25]
I've been using 0.1.1 of this module for a while and recently upgraded to 0.1.2. It installed a new version of syslinux according to 6707251bea2a174eb32a0e9fd59f0be5cf62b3ec but this resulted in a non-working installation, failing with 

```
failed to load com32 file menu.c32
```

This is a problem with mismatched versions of syslinux and I was able to fix it by doing `rm -rf /srv/tftp` and doing a Puppet run to allow this module to replace all the files. It works now, but maybe this module should have some code to properly wipe and rewrite the syslinux files to give smooth migration when changing version?

Cheers,
Jonathan

**Comment by xaque208** [comment]
Bummer, sorry for the trouble.  I'd think that the module should overwrite the files in the `/srv/tftp` directory.  Is this not the case?

**Comment by djjudas21** [comment]
It looks like anything that was in the *new* distribution of syslinux overwrote anything with the same name, but some files were orphaned in the old version and were never replaced. And I guess my PXE client was asking for the wrong versions? Not too sure.

I kept the contents of the original tftp directory - does this help?

```
[jg4461@infrastructure srv]$ pwd
/srv
[jg4461@infrastructure srv]$ diff tftp.old tftp
Common subdirectories: tftp.old/images and tftp/images
Only in tftp.old: memdisk
Only in tftp.old: menu.c32
Common subdirectories: tftp.old/pxelinux.cfg and tftp/pxelinux.cfg
Only in tftp.old: reboot.c32
Common subdirectories: tftp.old/syslinux and tftp/syslinux
Common subdirectories: tftp.old/tools and tftp/tools
Only in tftp.old: vesamenu.c32
```

**Comment by xaque208** [comment]
So if you place the old directory back to the original state, and remove reboot.c32, vesamenu.c32, memdisk and menu.c32, does it work correctly?  If so, we might just remove those files in the module to handle the upgrade.

**Comment by xaque208** [comment]
Is this still an issue for you @djjudas21 ?

**Comment by djjudas21** [comment]
We haven't run into it for a while, but I'm not sure if it's still an issue. I'm happy for you to close the issue and I'll open a new one if I run into anything in future :+1:
