### ISSUE TITLE
Release 0.1.4

### ISSUE THREAD

**Issue by djjudas21** [xaque208/puppet-pxe#28]
Please would you consider making a minor release to include the bugfix from #27?

Thanks,
Jonathan

**Comment by xaque208** [comment]
Oh sure, one sec.

**Comment by xaque208** [comment]
I've tagged 0.1.4, it should post to forge in the next few minutes.

**Comment by xaque208** [comment]
Posted.

**Comment by djjudas21** [comment]
10/10, A+++++, would fork again :smile:
